# name: ci

# on:
#   schedule:
#     - cron: "0 10 * * *"
#   push:
#     branches:
#       - "**"
#     tags:
#       - "v*.*.*"
#   pull_request:

# env:
#     REGISTRY: ghcr.io
#     IMAGE_NAME: ${{ github.repository }}

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup jdk 17
#         uses: actions/setup-java@v4
#         with:
#           java-version: '17'
#           distribution: 'temurin'
      
#       - name: Setup gradle
#         uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        
#       - name: Build with gradle wrapper
#         run: ./gradlew build
      
#     #   - name: Docker meta
#     #     id: meta
#     #     uses: docker/metadata-action@v5
#     #     with:
#     #       # list of Docker images to use as base name for tags
#     #       image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
      
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
      
#       - name: Login to Docker Hub
#         if: github.event_name != 'pull_request'
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
#       - name: Login to GHCR
#         if: github.event_name != 'pull_request'
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.GHCR_TOKEN }}
      
#       - name: Build and push
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           push: true
#           tags: ghcr.io/${{ github.repository_owner }}/rest-api:latest
#           run: |
#             docker build . -t ghcr.io/${{ github.repository_owner }}/rest-api:latest
#             docker push ghcr.io/${{ github.repository_owner }}/rest-api:latest