name: CD

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup jdk 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        
      - name: Build with gradle wrapper
        run: ./gradlew build
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" 
          docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
        #   tags: ghcr.io/${{ github.repository_owner }}/rest-api:latest
          run: |
            docker build . -t ghcr.io/Sava-VietNam/springboot-cicd-sample/rest-api:latest
            docker push ghcr.io/Sava-VietNam/springboot-cicd-sample/rest-api:latest