name: Build and deploy springboot-api
on:
    push:
      branches: [ "prod" ]
    pull_request:
      branches: [ "prod" ]

jobs:
  build-deploy:
    name: Build and deploy springboot-api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup jdk 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'

    #   - name: unit tests
    #     run: mvn -B test --file pom.xml
      
    #   - name: SonarQube Scan
    #     uses: kitabisa/sonarqube-action@v1.2.0
    #     env:
    #       SONAR_SCANNER_OPTS: -X
    #     with:
    #       host: ${{ secrets.SONARQUBE_HOST }}
    #       login: ${{ secrets.SONARQUBE_TOKEN }}
    #       projectBaseDir: "src/"
    #       projectKey: "my-custom-project"
        
       
    #   - name: build the app
    #     run: |
    #       mvn clean
    #       mvn -B package --file pom.xml
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        
      - name: Build with gradle wrapper
        run: ./gradlew build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
            context: .
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/rest-api:latest